// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package shield.kvstore.protobuf;

public final class HttpResponseProtos {
    private HttpResponseProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface ProtoResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:foobar.ProtoResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 status = 1;</code>
         */
        boolean hasStatus();
        /**
         * <code>required int32 status = 1;</code>
         */
        int getStatus();

        /**
         * <code>required bytes data = 2;</code>
         */
        boolean hasData();
        /**
         * <code>required bytes data = 2;</code>
         */
        com.google.protobuf.ByteString getData();

        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader>
        getHeadersList();
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader getHeaders(int index);
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        int getHeadersCount();
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        java.util.List<? extends shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder>
        getHeadersOrBuilderList();
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder getHeadersOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code foobar.ProtoResponse}
     */
    public static final class ProtoResponse extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:foobar.ProtoResponse)
            ProtoResponseOrBuilder {
        // Use ProtoResponse.newBuilder() to construct.
        private ProtoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private ProtoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final ProtoResponse defaultInstance;
        public static ProtoResponse getDefaultInstance() {
            return defaultInstance;
        }

        public ProtoResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private ProtoResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            status_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            data_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                headers_ = new java.util.ArrayList<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            headers_.add(input.readMessage(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    headers_ = java.util.Collections.unmodifiableList(headers_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.class, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.Builder.class);
        }

        public static com.google.protobuf.Parser<ProtoResponse> PARSER =
                new com.google.protobuf.AbstractParser<ProtoResponse>() {
                    public ProtoResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new ProtoResponse(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<ProtoResponse> getParserForType() {
            return PARSER;
        }

        public interface ProtoHeaderOrBuilder extends
                // @@protoc_insertion_point(interface_extends:foobar.ProtoResponse.ProtoHeader)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>required string name = 1;</code>
             */
            boolean hasName();
            /**
             * <code>required string name = 1;</code>
             */
            java.lang.String getName();
            /**
             * <code>required string name = 1;</code>
             */
            com.google.protobuf.ByteString
            getNameBytes();

            /**
             * <code>required string value = 2;</code>
             */
            boolean hasValue();
            /**
             * <code>required string value = 2;</code>
             */
            java.lang.String getValue();
            /**
             * <code>required string value = 2;</code>
             */
            com.google.protobuf.ByteString
            getValueBytes();
        }
        /**
         * Protobuf type {@code foobar.ProtoResponse.ProtoHeader}
         */
        public static final class ProtoHeader extends
                com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:foobar.ProtoResponse.ProtoHeader)
                ProtoHeaderOrBuilder {
            // Use ProtoHeader.newBuilder() to construct.
            private ProtoHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }
            private ProtoHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

            private static final ProtoHeader defaultInstance;
            public static ProtoHeader getDefaultInstance() {
                return defaultInstance;
            }

            public ProtoHeader getDefaultInstanceForType() {
                return defaultInstance;
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;
            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }
            private ProtoHeader(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000001;
                                name_ = bs;
                                break;
                            }
                            case 18: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000002;
                                value_ = bs;
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_ProtoHeader_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_ProtoHeader_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.class, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder.class);
            }

            public static com.google.protobuf.Parser<ProtoHeader> PARSER =
                    new com.google.protobuf.AbstractParser<ProtoHeader>() {
                        public ProtoHeader parsePartialFrom(
                                com.google.protobuf.CodedInputStream input,
                                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                throws com.google.protobuf.InvalidProtocolBufferException {
                            return new ProtoHeader(input, extensionRegistry);
                        }
                    };

            @java.lang.Override
            public com.google.protobuf.Parser<ProtoHeader> getParserForType() {
                return PARSER;
            }

            private int bitField0_;
            public static final int NAME_FIELD_NUMBER = 1;
            private java.lang.Object name_;
            /**
             * <code>required string name = 1;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string name = 1;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                }
            }
            /**
             * <code>required string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int VALUE_FIELD_NUMBER = 2;
            private java.lang.Object value_;
            /**
             * <code>required string value = 2;</code>
             */
            public boolean hasValue() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required string value = 2;</code>
             */
            public java.lang.String getValue() {
                java.lang.Object ref = value_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        value_ = s;
                    }
                    return s;
                }
            }
            /**
             * <code>required string value = 2;</code>
             */
            public com.google.protobuf.ByteString
            getValueBytes() {
                java.lang.Object ref = value_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private void initFields() {
                name_ = "";
                value_ = "";
            }
            private byte memoizedIsInitialized = -1;
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                if (!hasName()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                if (!hasValue()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(1, getNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(2, getValueBytes());
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;
            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(1, getNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(2, getValueBytes());
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;
            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static Builder newBuilder() { return Builder.create(); }
            public Builder newBuilderForType() { return newBuilder(); }
            public static Builder newBuilder(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader prototype) {
                return newBuilder().mergeFrom(prototype);
            }
            public Builder toBuilder() { return newBuilder(this); }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            /**
             * Protobuf type {@code foobar.ProtoResponse.ProtoHeader}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:foobar.ProtoResponse.ProtoHeader)
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_ProtoHeader_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_ProtoHeader_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.class, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder.class);
                }

                // Construct using shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }
                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    name_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    value_ = "";
                    bitField0_ = (bitField0_ & ~0x00000002);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_ProtoHeader_descriptor;
                }

                public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader getDefaultInstanceForType() {
                    return shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.getDefaultInstance();
                }

                public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader build() {
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader buildPartial() {
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader result = new shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.name_ = name_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.value_ = value_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader) {
                        return mergeFrom((shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader)other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader other) {
                    if (other == shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.getDefaultInstance()) return this;
                    if (other.hasName()) {
                        bitField0_ |= 0x00000001;
                        name_ = other.name_;
                        onChanged();
                    }
                    if (other.hasValue()) {
                        bitField0_ |= 0x00000002;
                        value_ = other.value_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    if (!hasName()) {

                        return false;
                    }
                    if (!hasValue()) {

                        return false;
                    }
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader) e.getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }
                private int bitField0_;

                private java.lang.Object name_ = "";
                /**
                 * <code>required string name = 1;</code>
                 */
                public boolean hasName() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }
                /**
                 * <code>required string name = 1;</code>
                 */
                public java.lang.String getName() {
                    java.lang.Object ref = name_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            name_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>required string name = 1;</code>
                 */
                public com.google.protobuf.ByteString
                getNameBytes() {
                    java.lang.Object ref = name_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        name_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder setName(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    name_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder clearName() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    name_ = getDefaultInstance().getName();
                    onChanged();
                    return this;
                }
                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder setNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    name_ = value;
                    onChanged();
                    return this;
                }

                private java.lang.Object value_ = "";
                /**
                 * <code>required string value = 2;</code>
                 */
                public boolean hasValue() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }
                /**
                 * <code>required string value = 2;</code>
                 */
                public java.lang.String getValue() {
                    java.lang.Object ref = value_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            value_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>required string value = 2;</code>
                 */
                public com.google.protobuf.ByteString
                getValueBytes() {
                    java.lang.Object ref = value_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        value_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>required string value = 2;</code>
                 */
                public Builder setValue(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    value_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>required string value = 2;</code>
                 */
                public Builder clearValue() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    value_ = getDefaultInstance().getValue();
                    onChanged();
                    return this;
                }
                /**
                 * <code>required string value = 2;</code>
                 */
                public Builder setValueBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    value_ = value;
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:foobar.ProtoResponse.ProtoHeader)
            }

            static {
                defaultInstance = new ProtoHeader(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:foobar.ProtoResponse.ProtoHeader)
        }

        private int bitField0_;
        public static final int STATUS_FIELD_NUMBER = 1;
        private int status_;
        /**
         * <code>required int32 status = 1;</code>
         */
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 status = 1;</code>
         */
        public int getStatus() {
            return status_;
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString data_;
        /**
         * <code>required bytes data = 2;</code>
         */
        public boolean hasData() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes data = 2;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int HEADERS_FIELD_NUMBER = 3;
        private java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader> headers_;
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        public java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader> getHeadersList() {
            return headers_;
        }
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        public java.util.List<? extends shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder>
        getHeadersOrBuilderList() {
            return headers_;
        }
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        public int getHeadersCount() {
            return headers_.size();
        }
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader getHeaders(int index) {
            return headers_.get(index);
        }
        /**
         * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
         */
        public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder getHeadersOrBuilder(
                int index) {
            return headers_.get(index);
        }

        private void initFields() {
            status_ = 0;
            data_ = com.google.protobuf.ByteString.EMPTY;
            headers_ = java.util.Collections.emptyList();
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasStatus()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasData()) {
                memoizedIsInitialized = 0;
                return false;
            }
            for (int i = 0; i < getHeadersCount(); i++) {
                if (!getHeaders(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, status_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, data_);
            }
            for (int i = 0; i < headers_.size(); i++) {
                output.writeMessage(3, headers_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, status_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, data_);
            }
            for (int i = 0; i < headers_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, headers_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code foobar.ProtoResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:foobar.ProtoResponse)
                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.class, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.Builder.class);
            }

            // Construct using shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getHeadersFieldBuilder();
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                status_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                data_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                if (headersBuilder_ == null) {
                    headers_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    headersBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return shield.kvstore.protobuf.HttpResponseProtos.internal_static_foobar_ProtoResponse_descriptor;
            }

            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse getDefaultInstanceForType() {
                return shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.getDefaultInstance();
            }

            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse build() {
                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse buildPartial() {
                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse result = new shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.status_ = status_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.data_ = data_;
                if (headersBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        headers_ = java.util.Collections.unmodifiableList(headers_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.headers_ = headers_;
                } else {
                    result.headers_ = headersBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse) {
                    return mergeFrom((shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse other) {
                if (other == shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.getDefaultInstance()) return this;
                if (other.hasStatus()) {
                    setStatus(other.getStatus());
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (headersBuilder_ == null) {
                    if (!other.headers_.isEmpty()) {
                        if (headers_.isEmpty()) {
                            headers_ = other.headers_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureHeadersIsMutable();
                            headers_.addAll(other.headers_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.headers_.isEmpty()) {
                        if (headersBuilder_.isEmpty()) {
                            headersBuilder_.dispose();
                            headersBuilder_ = null;
                            headers_ = other.headers_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            headersBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getHeadersFieldBuilder() : null;
                        } else {
                            headersBuilder_.addAllMessages(other.headers_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasStatus()) {

                    return false;
                }
                if (!hasData()) {

                    return false;
                }
                for (int i = 0; i < getHeadersCount(); i++) {
                    if (!getHeaders(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int status_ ;
            /**
             * <code>required int32 status = 1;</code>
             */
            public boolean hasStatus() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required int32 status = 1;</code>
             */
            public int getStatus() {
                return status_;
            }
            /**
             * <code>required int32 status = 1;</code>
             */
            public Builder setStatus(int value) {
                bitField0_ |= 0x00000001;
                status_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 status = 1;</code>
             */
            public Builder clearStatus() {
                bitField0_ = (bitField0_ & ~0x00000001);
                status_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>required bytes data = 2;</code>
             */
            public boolean hasData() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required bytes data = 2;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }
            /**
             * <code>required bytes data = 2;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                data_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required bytes data = 2;</code>
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000002);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader> headers_ =
                    java.util.Collections.emptyList();
            private void ensureHeadersIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    headers_ = new java.util.ArrayList<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader>(headers_);
                    bitField0_ |= 0x00000004;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder> headersBuilder_;

            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader> getHeadersList() {
                if (headersBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(headers_);
                } else {
                    return headersBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public int getHeadersCount() {
                if (headersBuilder_ == null) {
                    return headers_.size();
                } else {
                    return headersBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader getHeaders(int index) {
                if (headersBuilder_ == null) {
                    return headers_.get(index);
                } else {
                    return headersBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder setHeaders(
                    int index, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader value) {
                if (headersBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHeadersIsMutable();
                    headers_.set(index, value);
                    onChanged();
                } else {
                    headersBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder setHeaders(
                    int index, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder builderForValue) {
                if (headersBuilder_ == null) {
                    ensureHeadersIsMutable();
                    headers_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    headersBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder addHeaders(shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader value) {
                if (headersBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHeadersIsMutable();
                    headers_.add(value);
                    onChanged();
                } else {
                    headersBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder addHeaders(
                    int index, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader value) {
                if (headersBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHeadersIsMutable();
                    headers_.add(index, value);
                    onChanged();
                } else {
                    headersBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder addHeaders(
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder builderForValue) {
                if (headersBuilder_ == null) {
                    ensureHeadersIsMutable();
                    headers_.add(builderForValue.build());
                    onChanged();
                } else {
                    headersBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder addHeaders(
                    int index, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder builderForValue) {
                if (headersBuilder_ == null) {
                    ensureHeadersIsMutable();
                    headers_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    headersBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder addAllHeaders(
                    java.lang.Iterable<? extends shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader> values) {
                if (headersBuilder_ == null) {
                    ensureHeadersIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, headers_);
                    onChanged();
                } else {
                    headersBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder clearHeaders() {
                if (headersBuilder_ == null) {
                    headers_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    headersBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public Builder removeHeaders(int index) {
                if (headersBuilder_ == null) {
                    ensureHeadersIsMutable();
                    headers_.remove(index);
                    onChanged();
                } else {
                    headersBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder getHeadersBuilder(
                    int index) {
                return getHeadersFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder getHeadersOrBuilder(
                    int index) {
                if (headersBuilder_ == null) {
                    return headers_.get(index);  } else {
                    return headersBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public java.util.List<? extends shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder>
            getHeadersOrBuilderList() {
                if (headersBuilder_ != null) {
                    return headersBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(headers_);
                }
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder addHeadersBuilder() {
                return getHeadersFieldBuilder().addBuilder(
                        shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.getDefaultInstance());
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder addHeadersBuilder(
                    int index) {
                return getHeadersFieldBuilder().addBuilder(
                        index, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.getDefaultInstance());
            }
            /**
             * <code>repeated .foobar.ProtoResponse.ProtoHeader headers = 3;</code>
             */
            public java.util.List<shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder>
            getHeadersBuilderList() {
                return getHeadersFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilder<
                    shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder>
            getHeadersFieldBuilder() {
                if (headersBuilder_ == null) {
                    headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeader.Builder, shield.kvstore.protobuf.HttpResponseProtos.ProtoResponse.ProtoHeaderOrBuilder>(
                            headers_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    headers_ = null;
                }
                return headersBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:foobar.ProtoResponse)
        }

        static {
            defaultInstance = new ProtoResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:foobar.ProtoResponse)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_foobar_ProtoResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_foobar_ProtoResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_foobar_ProtoResponse_ProtoHeader_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_foobar_ProtoResponse_ProtoHeader_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016response.proto\022\006foobar\"\215\001\n\rProtoRespon" +
                        "se\022\016\n\006status\030\001 \002(\005\022\014\n\004data\030\002 \002(\014\0222\n\007head" +
                        "ers\030\003 \003(\0132!.foobar.ProtoResponse.ProtoHe" +
                        "ader\032*\n\013ProtoHeader\022\014\n\004name\030\001 \002(\t\022\r\n\005val" +
                        "ue\030\002 \002(\tB%\n\017shield.kvstore.protobufB\022HttpRespons" +
                        "eProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_foobar_ProtoResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_foobar_ProtoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_foobar_ProtoResponse_descriptor,
                new java.lang.String[] { "Status", "Data", "Headers", });
        internal_static_foobar_ProtoResponse_ProtoHeader_descriptor =
                internal_static_foobar_ProtoResponse_descriptor.getNestedTypes().get(0);
        internal_static_foobar_ProtoResponse_ProtoHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_foobar_ProtoResponse_ProtoHeader_descriptor,
                new java.lang.String[] { "Name", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
